[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Josefowicz_Lab"
authors = [{name = "Reshma Ramaiah", email = "rer4011@med.cornell.edu"}]
dynamic = ["version", "description"]
